server:
  servlet.contextPath: /api
  port: ${port:9200}

spring:
  data:
    mongodb:
      host: ${MONGO_HOST:localhost}
      port: ${MONGO_PORT:27017}
      username: ${MONGO_USER:foouser}
      password: ${MONGO_PASSWORD:foopwd}
      database: ${MONGO_DATABASE:admin}
