server:
  servlet.contextPath: /api
  port: 9200

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      username: ${MONGO_USER:testUser}
      password: ${MONGO_PASSWORD:testPassword}
      database: ${MONGO_DATABASE:testDatabase}
